export const CAMEROONIAN_MEDICATIONS = [
    'Artemether-Lumefantrine',
    'Artesunate',
    'Amoxicillin',
    'Cotrimoxazole',
    'Metronidazole',
    'Ciprofloxacin',
    'Doxycycline',
    'Chloroquine',
    'Paracetamol',
    'Ibuprofen',
    'Aspirin',
    'Omeprazole',
    'Metformin',
    'Glibenclamide',
    'Amlodipine',
    'Lisinopril',
    'Hydrochlorothiazide',
    'Atenolol',
    'Furosemide',
    'Spironolactone',
    'Salbutamol',
    'Prednisolone',
    'Dexamethasone',
    'Ferrous Sulfate',
    'Folic Acid',
    'Vitamin B Complex',
    'Zinc Sulfate',
    'Oral Rehydration Salts',
    'Mebendazole',
    'Albendazole',
    'Fluconazole',
    'Nystatin',
    'Acyclovir',
    'Tenofovir',
    'Lamivudine',
    'Efavirenz',
    'Nevirapine',
    'Lopinavir/Ritonavir',
    'Isoniazid',
    'Rifampicin',
    'Pyrazinamide',
    'Ethambutol',
    'Streptomycin',
    'Diazepam',
    'Phenobarbital',
    'Carbamazepine',
    'Haloperidol',
    'Chlorpromazine',
    'Morphine',
    'Tramadol',
];